### ISSUE TITLE
[Question] TUID vs. UUID v1

### ISSUE THREAD

**Issue by RyanBertrand** [tanglebones/pg_tuid#2]
Hey,

Sorry for the 'issue' question.  Is there any benefit to using this over UUID v1 (time based UUID)?

Thanks,
Ryan

**Comment by tanglebones** [comment]
v1 uuid's wrap around fairly quickly in my tests.

Generating 3 quickly:

     0ce86048-18a2-11e7-86b9-c4b301ba60d1
     0ddd9cde-18a2-11e7-86b9-c4b301ba60d1
     0f138cee-18a2-11e7-86b9-c4b301ba60d1

Shows the string representation sort order (0c3 0dd 0f1) will wrap around in a few minutes.

TUIDs also do not leak out the MAC address and can be generated easily on the client side for cases where you want to submit multiple related updates across tables in a single request to the server. (i.e. client -> server -> db)

(sorry for the delay in answering, I need to fix my email filters.)
